export const SIGN_UP = "SIGN_UP";
export const LOG_IN = "LOG_IN";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const RESET_ERROR_MESSAGE="RESET_ERROR_MESSAGE"
export const CHECK_USER_STATE="CHECK_USER_STATE"
export const GET_IMAGES="GET_IMAGES"
export const PUT_IMAGES="PUT_IMAGES"